// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20191016183353_001_InitDB")]
    partial class _001_InitDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Persistence.DatabaseContext+Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtistId");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 1,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            Name = "Villains"
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 1,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            Name = "...Like Clockwork"
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 2,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            Name = "Led Zeppelin II"
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 2,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            Name = "Led Zeppelin IV"
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 3,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            Name = "Masters of Reality"
                        },
                        new
                        {
                            Id = 6,
                            ArtistId = 3,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            Name = "Paranoid"
                        },
                        new
                        {
                            Id = 7,
                            ArtistId = 4,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            Name = "This Land"
                        },
                        new
                        {
                            Id = 8,
                            ArtistId = 5,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            Name = "Them Crooked Vultures"
                        },
                        new
                        {
                            Id = 9,
                            ArtistId = 6,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            Name = "\"Let's Rock\""
                        },
                        new
                        {
                            Id = 10,
                            ArtistId = 6,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            Name = "El Camino"
                        },
                        new
                        {
                            Id = 11,
                            ArtistId = 7,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            Name = "Laugh? I Nearly Bought One!"
                        },
                        new
                        {
                            Id = 12,
                            ArtistId = 7,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            Name = "Absolute Dissent"
                        },
                        new
                        {
                            Id = 13,
                            ArtistId = 7,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            Name = "Brighter Than A Thousand Suns"
                        },
                        new
                        {
                            Id = 14,
                            ArtistId = 8,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            Name = "Specter At The  Feast"
                        },
                        new
                        {
                            Id = 15,
                            ArtistId = 8,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            Name = "B.R.M.C."
                        });
                });

            modelBuilder.Entity("Persistence.DatabaseContext+Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            Name = "Queens of the Stone Age"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            Name = "Led Zeppelin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            Name = "Black Sabbath"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            Name = "Gary Clark Jr."
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            Name = "Them Crooked Vultures"
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            Name = "Black Keys"
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            Name = "Killing Joke"
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            Name = "Black Rebel Motorcycle Club"
                        });
                });

            modelBuilder.Entity("Persistence.DatabaseContext+Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Name");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Playlists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2019, 10, 13, 20, 12, 32, 0, DateTimeKind.Local),
                            Name = "Walk Like a Badass",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2019, 8, 22, 12, 52, 18, 0, DateTimeKind.Local),
                            Name = "Mellow Rock",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2018, 12, 30, 15, 2, 25, 0, DateTimeKind.Local),
                            Name = "Music to Focus",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2018, 10, 5, 10, 36, 10, 0, DateTimeKind.Local),
                            Name = "Oldschool Goodness",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Persistence.DatabaseContext+Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumId");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsExplicit");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 1,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            IsExplicit = false,
                            Name = "Feet Don't Fail Me"
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 1,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            IsExplicit = false,
                            Name = "The Evil Has Landed"
                        },
                        new
                        {
                            Id = 3,
                            AlbumId = 2,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            IsExplicit = false,
                            Name = "I Appear Missing"
                        },
                        new
                        {
                            Id = 4,
                            AlbumId = 2,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            IsExplicit = false,
                            Name = "Kalopsia"
                        },
                        new
                        {
                            Id = 5,
                            AlbumId = 3,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            IsExplicit = false,
                            Name = "Ramble On"
                        },
                        new
                        {
                            Id = 6,
                            AlbumId = 3,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            IsExplicit = false,
                            Name = "Whole Lotta Love"
                        },
                        new
                        {
                            Id = 7,
                            AlbumId = 4,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            IsExplicit = false,
                            Name = "Black Dog"
                        },
                        new
                        {
                            Id = 8,
                            AlbumId = 4,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            IsExplicit = false,
                            Name = "Rock and Roll"
                        },
                        new
                        {
                            Id = 9,
                            AlbumId = 4,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            IsExplicit = false,
                            Name = "Going to California"
                        },
                        new
                        {
                            Id = 10,
                            AlbumId = 5,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            IsExplicit = false,
                            Name = "Into the Void"
                        },
                        new
                        {
                            Id = 11,
                            AlbumId = 6,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            IsExplicit = false,
                            Name = "War Pigs"
                        },
                        new
                        {
                            Id = 12,
                            AlbumId = 6,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            IsExplicit = false,
                            Name = "Fairies Wear Boots"
                        },
                        new
                        {
                            Id = 13,
                            AlbumId = 7,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            IsExplicit = false,
                            Name = "Pearl Cadillac"
                        },
                        new
                        {
                            Id = 14,
                            AlbumId = 7,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            IsExplicit = false,
                            Name = "I Walk Alone"
                        },
                        new
                        {
                            Id = 15,
                            AlbumId = 7,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            IsExplicit = false,
                            Name = "The Guitar Man"
                        },
                        new
                        {
                            Id = 16,
                            AlbumId = 8,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            IsExplicit = false,
                            Name = "Gunman"
                        },
                        new
                        {
                            Id = 17,
                            AlbumId = 9,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            IsExplicit = false,
                            Name = "Eagle Birds"
                        },
                        new
                        {
                            Id = 18,
                            AlbumId = 10,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            IsExplicit = false,
                            Name = "Run Right Back"
                        },
                        new
                        {
                            Id = 19,
                            AlbumId = 10,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            IsExplicit = false,
                            Name = "Sister"
                        },
                        new
                        {
                            Id = 20,
                            AlbumId = 11,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            IsExplicit = false,
                            Name = "Requiem"
                        },
                        new
                        {
                            Id = 21,
                            AlbumId = 12,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            IsExplicit = false,
                            Name = "The Raven King"
                        },
                        new
                        {
                            Id = 22,
                            AlbumId = 13,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            IsExplicit = false,
                            Name = "Love of the Masses"
                        },
                        new
                        {
                            Id = 23,
                            AlbumId = 14,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            IsExplicit = false,
                            Name = "Funny Games"
                        },
                        new
                        {
                            Id = 24,
                            AlbumId = 15,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            IsExplicit = false,
                            Name = "Red Eyes And Tears"
                        },
                        new
                        {
                            Id = 25,
                            AlbumId = 15,
                            CreatedOn = new DateTime(1990, 1, 1, 13, 0, 0, 0, DateTimeKind.Local),
                            IsExplicit = false,
                            Name = "As Sure As The Sun"
                        });
                });

            modelBuilder.Entity("Persistence.DatabaseContext+TrackPlaylistAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedTrackToPlaylistOn");

                    b.Property<int>("PlaylistId");

                    b.Property<int>("TrackId");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("TrackId");

                    b.ToTable("TrackPlaylistAssignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedTrackToPlaylistOn = new DateTime(2019, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaylistId = 1,
                            TrackId = 17
                        },
                        new
                        {
                            Id = 2,
                            AddedTrackToPlaylistOn = new DateTime(2019, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaylistId = 1,
                            TrackId = 2
                        },
                        new
                        {
                            Id = 3,
                            AddedTrackToPlaylistOn = new DateTime(2019, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaylistId = 1,
                            TrackId = 1
                        },
                        new
                        {
                            Id = 4,
                            AddedTrackToPlaylistOn = new DateTime(2019, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaylistId = 1,
                            TrackId = 16
                        },
                        new
                        {
                            Id = 5,
                            AddedTrackToPlaylistOn = new DateTime(2019, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaylistId = 1,
                            TrackId = 18
                        },
                        new
                        {
                            Id = 6,
                            AddedTrackToPlaylistOn = new DateTime(2019, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaylistId = 1,
                            TrackId = 24
                        },
                        new
                        {
                            Id = 7,
                            AddedTrackToPlaylistOn = new DateTime(2019, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaylistId = 2,
                            TrackId = 4
                        },
                        new
                        {
                            Id = 8,
                            AddedTrackToPlaylistOn = new DateTime(2019, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaylistId = 2,
                            TrackId = 9
                        },
                        new
                        {
                            Id = 9,
                            AddedTrackToPlaylistOn = new DateTime(2019, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaylistId = 2,
                            TrackId = 21
                        },
                        new
                        {
                            Id = 10,
                            AddedTrackToPlaylistOn = new DateTime(2019, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaylistId = 2,
                            TrackId = 22
                        },
                        new
                        {
                            Id = 11,
                            AddedTrackToPlaylistOn = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaylistId = 2,
                            TrackId = 23
                        },
                        new
                        {
                            Id = 12,
                            AddedTrackToPlaylistOn = new DateTime(2019, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaylistId = 2,
                            TrackId = 25
                        },
                        new
                        {
                            Id = 13,
                            AddedTrackToPlaylistOn = new DateTime(2018, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaylistId = 3,
                            TrackId = 23
                        },
                        new
                        {
                            Id = 14,
                            AddedTrackToPlaylistOn = new DateTime(2018, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaylistId = 3,
                            TrackId = 9
                        },
                        new
                        {
                            Id = 15,
                            AddedTrackToPlaylistOn = new DateTime(2019, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaylistId = 3,
                            TrackId = 3
                        },
                        new
                        {
                            Id = 16,
                            AddedTrackToPlaylistOn = new DateTime(2019, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaylistId = 3,
                            TrackId = 4
                        },
                        new
                        {
                            Id = 17,
                            AddedTrackToPlaylistOn = new DateTime(2018, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaylistId = 4,
                            TrackId = 5
                        },
                        new
                        {
                            Id = 18,
                            AddedTrackToPlaylistOn = new DateTime(2018, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaylistId = 4,
                            TrackId = 6
                        },
                        new
                        {
                            Id = 19,
                            AddedTrackToPlaylistOn = new DateTime(2018, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaylistId = 4,
                            TrackId = 7
                        },
                        new
                        {
                            Id = 20,
                            AddedTrackToPlaylistOn = new DateTime(2018, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaylistId = 4,
                            TrackId = 8
                        },
                        new
                        {
                            Id = 21,
                            AddedTrackToPlaylistOn = new DateTime(2018, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaylistId = 4,
                            TrackId = 9
                        },
                        new
                        {
                            Id = 22,
                            AddedTrackToPlaylistOn = new DateTime(2018, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaylistId = 4,
                            TrackId = 10
                        },
                        new
                        {
                            Id = 23,
                            AddedTrackToPlaylistOn = new DateTime(2018, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaylistId = 4,
                            TrackId = 11
                        },
                        new
                        {
                            Id = 24,
                            AddedTrackToPlaylistOn = new DateTime(2018, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaylistId = 4,
                            TrackId = 12
                        });
                });

            modelBuilder.Entity("Persistence.DatabaseContext+User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("FirstName");

                    b.Property<DateTime>("LastAccessOn");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2016, 6, 13, 19, 41, 32, 643, DateTimeKind.Local).AddTicks(6241),
                            FirstName = "Daniel",
                            LastAccessOn = new DateTime(2019, 10, 14, 21, 31, 11, 535, DateTimeKind.Local).AddTicks(9553),
                            LastName = "Agg"
                        });
                });

            modelBuilder.Entity("Persistence.DatabaseContext+Album", b =>
                {
                    b.HasOne("Persistence.DatabaseContext+Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Persistence.DatabaseContext+Playlist", b =>
                {
                    b.HasOne("Persistence.DatabaseContext+User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Persistence.DatabaseContext+Track", b =>
                {
                    b.HasOne("Persistence.DatabaseContext+Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Persistence.DatabaseContext+TrackPlaylistAssignment", b =>
                {
                    b.HasOne("Persistence.DatabaseContext+Playlist", "Playlist")
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Persistence.DatabaseContext+Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
